### ISSUE TITLE
Port Triple Strange Swerve

### ISSUE THREAD

**Issue by bbooher** [bow4290/libbow#1]
Proposed folder structure:

<ul>
<li>modules</li>
<ul>
<li>drivetrain</li>
<ul>
<li>swerve</li>
<li>tank</li>
</ul>
<li>turret</li>
</ul>
<li>sensors</li>
<li>actuators</li>
</ul>

Start to port Triple Strange Swerve code into the swerve directory.

**Comment by apppppppple** [comment]
would drivetrain be for a traditional drivetrain?

**Comment by JumpingPistachio** [comment]
> would drivetrain be for a traditional drivetrain?

Same question here

**Comment by bbooher** [comment]
Swerve and tank should be subdirectories of drivetrain. I'll edit the task.

**Comment by JumpingPistachio** [comment]
Oh goodness I didn't realize that updated it each time, sorry!

**Comment by bbooher** [comment]
Also, the swerve/tank directories may not be needed. I'll leave that up to you all.

**Comment by bbooher** [comment]
Also also, feel free to break this down into more issues.
